services:
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./video_platform:/usr/src/app
    env_file: ./.env
    depends_on:
      pg_database:
        condition: service_healthy
    command: sh -c "python manage.py migrate && python manage.py runserver ${DOCKER_DJANGO_URL}"
    ports:
      - "${DOCKER_LOCAL_DJANGO_PORT}:${DOCKER_DJANGO_PORT}"
    restart: unless-stopped
    networks:
      - dev
  pg_database:
    image: postgres:18-alpine
    container_name: pg_database
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dev

volumes:
  pg_data:

networks:
  dev:
