[pytest]
testpaths = tests
asyncio_mode = auto
norecursedirs = logs database/migrations
addopts = -v --cov=. --cov-report=html:../htmlcovs
log_cli = true
log_cli_level = INFO
markers =
    unit: unit-tests
    integration: integration-tests
