"""Initial spimex

Revision ID: 70b27f21c580
Revises: 
Create Date: 2026-04-17 15:56:35.293178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b27f21c580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('code_item', sa.String(length=20), nullable=False, comment='Код инструмента'),
    sa.Column('name_item', sa.String(length=255), nullable=False, comment='Наименование инструмента'),
    sa.Column('basis_delivery', sa.String(length=255), nullable=False, comment='Базис поставки'),
    sa.Column('volume', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Объем договоров в единицах измерения'),
    sa.Column('volume_rub', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Объем договоров, руб.'),
    sa.Column('price_change_rub', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Изменение цены к цене предыдущего дня (руб.)'),
    sa.Column('price_change_percent', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Изменение цены к цене предыдущего дня (%)'),
    sa.Column('minimum_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Минимальная цена'),
    sa.Column('avg_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Средневзвешенная цена'),
    sa.Column('maximum_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Максимальная цена'),
    sa.Column('market_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Рыночная цена'),
    sa.Column('best_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Цена заявки (Лучшее предложение)'),
    sa.Column('best_demand', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Цена заявки (Лучший спрос)'),
    sa.Column('counter', sa.Integer(), nullable=True, comment='Количество сделок шт.'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex')
    # ### end Alembic commands ###
