# Generated by Django 6.0.3 on 2026-04-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Опубликовано ли видео', verbose_name='Опубликован')),
                ('name', models.CharField(help_text='Название загружаемого видео', max_length=100, verbose_name='Название')),
                ('total_likes', models.PositiveIntegerField(default=0, help_text='Количество лайков на видео', verbose_name='Лайки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда видео создано', verbose_name='Дата и время создания')),
                ('owner', models.ForeignKey(help_text='Создатель видео', on_delete=django.db.models.deletion.CASCADE, related_name='videos', related_query_name='video', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузка файл', upload_to='videos/', verbose_name='Файл')),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('FHD', 'FHD'), ('UHD', 'UHD')], default='HD', help_text='Качество видео (HD, FHD, UHD)', max_length=3, verbose_name='Качество')),
                ('video', models.ForeignKey(help_text='Ссылка на созданное видео', on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='video_app.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео файл',
                'verbose_name_plural': 'Видео файлы',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Пользователь, отправляющий лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(help_text='Лайк видео', on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to='video_app.video', verbose_name='Лайк')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'constraints': [models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user')],
            },
        ),
    ]
