name: FastAPI-run-test

on:
  push:
    branches: [main]
    paths:
      - 'fastapi_task/app/**'
      - 'fastapi_task/req.txt'
  pull_request:
    branches: [main]
    paths:
      - 'fastapi_task/app/**'
      - 'fastapi_task/req.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Cloning project
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependency
        working-directory: 'fastapi_task'
        run: |
          cp .env_example .env
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run tests
        working-directory: 'fastapi_task/app'
        run: |
          pytest --cov-report=term
