# Generated by Django 6.0.3 on 2026-04-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Полное название статьи', max_length=200, verbose_name='Название')),
                ('text', models.TextField(help_text='Текст статьи (ограничений нет)', verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания статьи (автоматическое устанавливает время)', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время обновления статьи (автоматическое устанавливает время)', verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликована'), ('AR', 'Архив')], default='DR', help_text='Статус статьи (черновик, опубликована, архив)', max_length=2, verbose_name='Статус')),
                ('slug', models.SlugField(help_text='URL-название статьи переведённая в транслит', max_length=255, unique=True, verbose_name='Слаг')),
                ('author', models.ForeignKey(help_text='Пользователь, который создал статью', on_delete=django.db.models.deletion.CASCADE, related_name='articles', related_query_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
